# Created using wingetcreate 1.2.2.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.4.0.schema.json

PackageIdentifier: Microsoft.VisualStudio.2022.Professional.Preview
PackageVersion: 17.10.0
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSuccessCodes:
- 1641
- 3010
Commands:
- devenv
Protocols:
- git-client
- vsls
- vssd
- vstfs
- vsweb
FileExtensions:
- asm
- asmx
- asp
- aspx
- c
- config
- cpp
- cppm
- cs
- csproj
- cxx
- h
- hpp
- hxx
- sln
- ts
- vcproj
- vcxproj
- xml
Installers:
- InstallerLocale: en-US
  Architecture: x64
  InstallerType: exe
  Scope: machine
  InstallerUrl: https://download.visualstudio.microsoft.com/download/pr/08784799-a959-4274-bbc5-a54ffebffeaf/600eec037c5f7e6d13cd0ec5852884007f11d18c908b66aa5466d370d761c902/vs_Professional.exe
  InstallerSha256: 600EEC037C5F7E6D13CD0EC5852884007F11D18C908B66AA5466D370D761C902
  InstallerSwitches:
    Silent: --add Microsoft.VisualStudio.Component.CoreEditor --quiet --norestart --wait
    SilentWithProgress: --add Microsoft.VisualStudio.Component.CoreEditor --passive --norestart --wait
    Interactive: --add Microsoft.VisualStudio.Workload.Universal --includeRecommended --wait
    InstallLocation: --installPath <INSTALLPATH>
  UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.4.0
