# Created using wingetcreate 1.2.2.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.4.0.schema.json

PackageIdentifier: Microsoft.VisualStudio.2022.Community
PackageVersion: 17.4.4
MinimumOSVersion: 10.0.0.0
InstallerSwitches:
  Silent: --quiet
  SilentWithProgress: --passive
  Upgrade: update
  Custom: --wait
ExpectedReturnCodes:
- InstallerReturnCode: 1001
  ReturnResponse: installInProgress
- InstallerReturnCode: 1003
  ReturnResponse: fileInUse
- InstallerReturnCode: 1641
  ReturnResponse: rebootInitiated
- InstallerReturnCode: 3010
  ReturnResponse: rebootRequiredToFinish
- InstallerReturnCode: -1073720687
  ReturnResponse: noNetwork
Commands:
- devenv
Installers:
- Architecture: x64
  InstallerType: burn
  InstallerUrl: https://download.visualstudio.microsoft.com/download/pr/0502e0d3-64a5-4bb8-b049-6bcbea5ed247/0ba87bfdbde662bb0f7631e4eafefe93f60bd8279407908c8a26a2a1ea4afff9/vs_Community.exe
  InstallerSha256: 0BA87BFDBDE662BB0F7631E4EAFEFE93F60BD8279407908C8A26A2A1EA4AFFF9
ManifestType: installer
ManifestVersion: 1.4.0
