# Created using wingetcreate 1.2.2.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.4.0.schema.json

PackageIdentifier: Microsoft.VisualStudio.2022.Enterprise.Preview
PackageVersion: 17.6.0
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSuccessCodes:
- 1641
- 3010
Commands:
- devenv
Protocols:
- git-client
- vsls
- vssd
- vstfs
- vsweb
FileExtensions:
- asm
- asmx
- asp
- aspx
- c
- config
- cpp
- cppm
- cs
- csproj
- cxx
- h
- hpp
- hxx
- sln
- ts
- vcproj
- vcxproj
- xml
Installers:
- InstallerLocale: en-US
  Architecture: x64
  InstallerType: exe
  Scope: machine
  InstallerUrl: https://download.visualstudio.microsoft.com/download/pr/7a8f3773-fe08-4071-bf65-e9564418dbd0/d12e00cdc35a3befca5396625320dc2ef87168302950cb7714365d28626416a6/vs_Enterprise.exe
  InstallerSha256: D12E00CDC35A3BEFCA5396625320DC2EF87168302950CB7714365D28626416A6
  InstallerSwitches:
    Silent: --add Microsoft.VisualStudio.Component.CoreEditor --quiet --norestart --wait
    SilentWithProgress: --add Microsoft.VisualStudio.Component.CoreEditor --passive --norestart --wait
    Interactive: --add Microsoft.VisualStudio.Workload.Universal --includeRecommended --wait
    InstallLocation: --installPath <INSTALLPATH>
  UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.4.0
