# Created using wingetcreate 1.2.2.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.4.0.schema.json

PackageIdentifier: Microsoft.VisualStudio.2022.Enterprise.Preview
PackageVersion: 17.10.0
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSuccessCodes:
- 1641
- 3010
Commands:
- devenv
Protocols:
- git-client
- vsls
- vssd
- vstfs
- vsweb
FileExtensions:
- asm
- asmx
- asp
- aspx
- c
- config
- cpp
- cppm
- cs
- csproj
- cxx
- h
- hpp
- hxx
- sln
- ts
- vcproj
- vcxproj
- xml
Installers:
- InstallerLocale: en-US
  Architecture: x64
  InstallerType: exe
  Scope: machine
  InstallerUrl: https://download.visualstudio.microsoft.com/download/pr/c5e4e47e-ae95-430b-b171-38acbc56439d/77d500e60213ce8c8fd9f08dfb4712a0d778d03565d1b6037856a6ca877e4975/vs_Enterprise.exe
  InstallerSha256: 77D500E60213CE8C8FD9F08DFB4712A0D778D03565D1B6037856A6CA877E4975
  InstallerSwitches:
    Silent: --add Microsoft.VisualStudio.Component.CoreEditor --quiet --norestart --wait
    SilentWithProgress: --add Microsoft.VisualStudio.Component.CoreEditor --passive --norestart --wait
    Interactive: --add Microsoft.VisualStudio.Workload.Universal --includeRecommended --wait
    InstallLocation: --installPath <INSTALLPATH>
  UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.4.0
